name:                pdevs
version:             0.1.0.0
github:              "alios/pdevs"
license:             BSD3
author:              "Markus Barenhoff"
maintainer:          "mbarenh@alios.org"
copyright:           "Copyright: (c) 2018 Markus Barenhoff"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alios/pdevs#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- vector

library:
  source-dirs: src
  ghc-options: -Wall

executables:
  pdevs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pdevs

tests:
  pdevs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pdevs
